### PR TITLE
Tasks have IAM Roles to allow access to other AWS services

### PR DESCRIPTION
**Pull request by shoan**
Create/Update of service, will create a service specific role and
attach it to every task via the task definition. By default, the role
has no permissions.

### CODE REVIEW

**Comment by shoan** [comment]
Supercedes #5

**Comment by siliconsenthil** [comment]
Nice. The idea is to have task roles associated with IAM access related stuff instead of creating a user and passing the credentials to the services to do certain AWS operations. Right? Any other benefits

@shoan

**Comment by shoan** [comment]
> Nice. The idea is to have task roles associated with IAM access related stuff instead of creating a user and passing the credentials to the services to do certain AWS operations. Right? Any other benefits
> 
> @shoan

That's it. There'll be no need to have AWS credentials either in the code or the config.

**Comment by siliconsenthil** [comment]
That makes sense.

But with AWS credentials as environment vars, it makes it easier to test from local using them. Now, if we need to test, they have to deploy to AWS. Is there any workaround for this?

**Comment by shoan** [comment]
This doesn't prevent you from doing what you mentioned.

**Comment by siliconsenthil** [comment]
Yeah. We assume for the service to run we need only the env vars mentioned in `env.sample` file. But, we don't have to specify for AWS as the task will do that via IAM roles.  

The environment variables are assumed to be implicitly available I guess. Also if there's code that initializes the AWS client explicitly using the environment variables, they have to make code changes to utilize IAM role-based access. 

Just mentioning here to be on same page.

**Comment by sannithibalaji** [comment]
env variables take higher precedence over IAM roles, so it backwards compatible as well.

**Pull request merged**
